apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: queue
  labels:
    app.kubernetes.io/instance: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  serviceName: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: rabbitmq:3.6.0
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_PASS
          value: mypass
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"

---

apiVersion: v1
kind: Service
metadata:
  name: queue
  labels:
    app.kubernetes.io/instance: django
spec:
  type: ClusterIP  
  ports:
  - name: queue
    port: 5672
  selector:
    app: queue
